### ISSUE TITLE
为什么要移除 tls_1.0_session和 tls_simple?

### ISSUE THREAD

**Issue by Danie1s** [yichengchen/ShadowsocksX-R#10]
很多ssr都是用 tls_1.0_session的

**Comment by yichengchen** [comment]
因为[ssr上游](https://github.com/breakwa11/shadowsocks-libev)移除了对这两个协议的支持 [remove tls1.0_session_auth, fix http_simple coredump if custom http head](https://github.com/breakwa11/shadowsocks-libev/commit/8dd3dabd5f39a9d9935059db14c5340ef77dee4d)

据称这两个协议的实现有着比较严重的问题，更容易被gfw屏蔽。
