### ISSUE TITLE
请问Mac版的服务器配置文件存放在哪里了

### ISSUE THREAD

**Issue by chingxuds** [yichengchen/ShadowsocksX-R#13]

**Comment by yichengchen** [comment]
在苹果提供的nsuserdefault接口里面，应该是程序目录下的某个plist文件

**Comment by chingxuds** [comment]
实际并未找到，有参考路径吗

**Comment by yichengchen** [comment]
~/Library/Preferences/com.yicheng.ShadowsocksX-R.plist

[StackOverflow -Where is a Mac Application's NSUserDefaults Data Stored?](http://stackoverflow.com/questions/7982740/where-is-a-mac-applications-nsuserdefaults-data-stored)
