### ISSUE TITLE
服务端配置fail2ban时，使用一段时间后会被ban

### ISSUE THREAD

**Issue by kid424** [yichengchen/ShadowsocksX-R#15]
由于部分网站限制IP归属地的关系，我把ShadowsocksX-R的PAC里面的端口改成了同台机器上跑的libev版客户端的端口，然后在Chrome上面使用SwitchyOmega访问ShadowsocksX-R上的服务器。libev客户端用的服务器和ShadowsocksX-R上的服务器是不一样的，不过都部署了fail2ban，一旦检测到24小时内密码错误（包括混淆错误）超过3次，就会ban掉访问IP。刚配置完后一切正常，使用Safari会走libev的服务器，使用Chrome访问墙外网站走ShadowsocksX-R的服务器。

现在的问题是，ShadowsocksX-R每次运行一段时间后，会发现我的本地IP被fail2ban给ban掉。服务器上的ssr版本通过git更新到最新版后这个问题也依然存在。之前使用python和libev的ssr客户端都没有这个问题。

版本：ssr_v1.3.5和ssr_v1.3.6
端口：80
加密方式：chacha20-ietf
协议：auth_sha1_v2
混淆：http_simple
混淆参数：留空和cloudflare.com都试过

**Comment by yichengchen** [comment]
新版同步了一下sslibev代码……可以再试一下，有问题的话貌似也没什么办法……因为这个程序界面和后台ss（ss-local)其实是完全分离的。。。所有请求都是由独立的ss-local完成的=、=
