### ISSUE TITLE
版本 ssr_v1.3.7 打开了测网速在 macOS Sierra 会闪退

### ISSUE THREAD

**Issue by coldice945** [yichengchen/ShadowsocksX-R#16]
RT。又因为已经打开了测网速的，所以会导致只要一打开GUI就会闪退打不开界面程序。只好下上一版覆盖。

**Comment by ookangzheng** [comment]
我的也是~~ 10.12會閃退

**Comment by yichengchen** [comment]
配置文件应该是在这，可以删掉……
~/Library/Preferences/com.yicheng.ShadowsocksX-R.plist

**Comment by honbolau** [comment]
由于macOS 10.12 删除了/usr/bin/sar 命令导致的错误

**Comment by VinkenCheng** [comment]
@alitime 还是闪退的话试下删除cache，路径~/Library/Caches/com.yicheng.ShadowsocksX-R
然后还是不行的话重启一次就好了。注意：貌似重启之后回丢失ShadowsocksX-R配置，重新配置就好
