### ISSUE TITLE
无法打开，闪退，求解决！

### ISSUE THREAD

**Issue by wle6** [yichengchen/ShadowsocksX-R#3]
ShadowsocksX-R.10.9.no.test.zip在osx10.9.5无法打开，图标出现马上闪退，请解决！

**Comment by yichengchen** [comment]
啊哈………这个嘛…很尴尬啊…没有这个系统的环境可以测试………尝试像上游反馈一下？讲道理我调整development target后编译没有warning不应该啊…

**Comment by wle6** [comment]
是不是下载后解压，就直接可以打开用了？

**Comment by yichengchen** [comment]
理论上是的   如果打不开的话可以尝试放到application文件夹后试试。不过10.9的系统真的没测试过………

**Comment by wle6** [comment]
已放到application，打开后ss图标在finder栏一闪而过，能不能装个10.9.5虚拟机测试一下啊。

**Comment by yichengchen** [comment]
唔…你可以clone项目在xcode里调试运行debug…或者到原项目shadowsocksx-ng中发issue。😂😂😂

**Comment by sec7et** [comment]
@yichengchen 
我这边是10.11的环境，装XR，打开也是闪退，小飞机图标出现一下就消失，提醒我配置服务器的弹窗会弹出来。电脑上装了surge for mac和shadowsocksX，不知道是否有影响呢。但是确实是打开就闪退
