### ISSUE TITLE
10.12.2 Safari 无法使用

### ISSUE THREAD

**Issue by BIOTONIC** [yichengchen/ShadowsocksX-R#40]
换了几个SS账号后发现都无法使用 更新到10.12.2就这样了 有遇到同样问题的嘛

**Comment by BIOTONIC** [comment]
另外发现X-R的Feedback链接到的是X-NG 能不能换过来啊

**Comment by yichengchen** [comment]
try download the newest version in another fork https://github.com/qinyuhang/ShadowsocksX-NG/releases

**Comment by BIOTONIC** [comment]
问题解决了 CleanMyMac->Extensions->Launch Agents中Enable ss的启动项就能启动ss-local了
