### ISSUE TITLE
服务器升级之后貌似就不能用了

### ISSUE THREAD

**Issue by vera-chan** [yichengchen/ShadowsocksX-R#44]
MAC是10.11.6的系统，之前ok的，前段时间服务器升级了一下，ios 和Windows改改参数可以正常连，但MAC就连不上了。报错好像是 cfwnetwork ssl handshake failed.

**Comment by yichengchen** [comment]
try download the newest version in another fork https://github.com/qinyuhang/ShadowsocksX-NG/releases
