### ISSUE TITLE
MAC 上使用 ShadowshockX-R的问题

### ISSUE THREAD

**Issue by chen6440320** [yichengchen/ShadowsocksX-R#6]
只有 chrome 能正常使用，自带的 Safari等其他类似 tweetbot 都无法使用，不知道是不是 bug。

**Comment by ltr970503** [comment]
10.11.6正常，检查一下代理配置看看

**Comment by chen6440320** [comment]
账号密码，ip，协议都是正确的，因为 chrome 是能正常代理的，但是 safari 不能代理

**Comment by chen6440320** [comment]
是因为我用的 macOS 的原因吗？

**Comment by yichengchen** [comment]
如果你是10.12版系统  请看这里 https://github.com/qiuyuzhou/ShadowsocksX-NG/issues/30 这是苹果的限制= =，我会紧跟上游更新。

**Comment by chen6440320** [comment]
明白了，谢谢~

**Comment by yichengchen** [comment]
新版本尝试进行了修复。
