### ISSUE TITLE
ss-local会一直在后台占用端口

### ISSUE THREAD

**Issue by DrawLi** [yichengchen/ShadowsocksX-R#7]
不知道是不是故意这样设计的。
运行shadowsocksX-R，点击“打开shadowsocks”以后，即使退出shadowsocksX-R，后台也会驻留一个ss-local进程并随开机启动(shadowsocksX-R没有设置开机启动）。
得点击“关闭shadow socks”，进程才会退出。

**Comment by itzhaclea** [comment]
參見原版 ShadowsocksX-NG 的說明：

> Run ss-local as backgroud service through launchd, not in app process. So after you quit the app, the ss-local maybe is still running.

**Comment by yichengchen** [comment]
新版本中尝试加入了在退出程序中尝试exit sslocal。

如果发现ss-local一直无法结束  尝试以下步骤。

```
cd $HOME/Library/LaunchAgents/
ls | grep socks
```

对列出来的项目分别执行

```
 launchctl unload com.yicheng.ShadowsocksX-R.plist （示例）
```

**Comment by wanghaixiang** [comment]
最好能增加服务器均衡的功能，能够增加按照ping延迟时间来自动选择服务器的功能，尝试加入的ping功能很鸡肋，基本上80%的服务器是ping不出延迟的。

**Comment by yichengchen** [comment]
这就是我一直说的ss-local与gui分离的缺陷所在，这些需要深度整合的功能很难实现,或者实现后用户感知会很差。

所以暂时只能先这样了😅
