### ISSUE TITLE
添加测量延时

### ISSUE THREAD

**Issue by wanghaixiang** [yichengchen/ShadowsocksX-R#8]
能不能添加测量延时的功能，可以增加一个功能，在所有服务器里ping延时最小的优先链接！

**Comment by yichengchen** [comment]
这个正在计划当中。由于本程序目前采用ss-local与gui界面分离方式，导致操作较为困难。可能需要重构解决，没那么快=、=

**Comment by yichengchen** [comment]
610f43d03cba268087929e5d01e5fefb42d364fe 简单实现了一下…下个版本发布
